name: civic_guard
version: "1.0.0"
config-version: 2

profile: civic_guard

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  civic_guard:
    +materialized: view
