# Generated by Django 6.0.5 on 2026-08-29 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('query_text', models.TextField()),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('model', models.CharField(db_index=True, max_length=128)),
                ('embedding_time_ms', models.FloatField(blank=True, null=True)),
                ('retrieval_time_ms', models.FloatField(blank=True, null=True)),
                ('generation_time_ms', models.FloatField(blank=True, null=True)),
                ('total_time_ms', models.FloatField(blank=True, null=True)),
                ('tokens_generated', models.IntegerField(blank=True, null=True)),
                ('tokens_generated_is_estimate', models.BooleanField(default=False)),
                ('tokens_per_second', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'rag_request_metrics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
