# Generated by Django 6.0.5 on 2026-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('matched_ground_truth', models.BooleanField(default=False)),
                ('keyword_coverage', models.FloatField(blank=True, null=True)),
                ('keyword_source', models.CharField(blank=True, default='', max_length=16)),
                ('retrieved_section_ids', models.JSONField(blank=True, default=list)),
                ('response_chars', models.IntegerField(blank=True, null=True)),
                ('target_section', models.CharField(blank=True, default='', max_length=64)),
                ('hit', models.BooleanField(blank=True, null=True)),
                ('reciprocal_rank', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eval_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
