# Generated by Django 6.0.5 on 2026-08-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_engine', '0002_evalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmetric',
            name='chain_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='classify_label',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='classify_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='retrieval_calls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='retrieve_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='verify_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='verify_retry',
            field=models.BooleanField(default=False),
        ),
    ]
