# Generated by Django 6.0.5 on 2026-08-29 11:49

import django.db.models.deletion
import rag_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_engine', '0003_requestmetric_chain_ms_requestmetric_classify_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=rag_engine.models.generate_api_key, max_length=64, unique=True)),
                ('owner', models.CharField(help_text='Owner / team name', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('requests_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key_owner', models.CharField(blank=True, default='', max_length=120)),
                ('api_key_hint', models.CharField(blank=True, default='', max_length=20)),
                ('method', models.CharField(max_length=8)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='rag_engine.apikey')),
            ],
            options={
                'db_table': 'request_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
