# Generated by Django 6.0.5 on 2026-08-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_engine', '0004_apikey_requestauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmetric',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
